title = "A Hugo theme for creating Reveal.js presentations"
baseUrl = "https://charrismatic.github.io/learn-about-github/"
publicDir = "../docs"
#languageCode = "en-us"

disableKinds = ["sitemap", "RSS"]
theme = "reveal-hugo"

# themesDir = "."
[author]
name = "Matt Harris"


[markup.goldmark.renderer]
unsafe = true
languageCode = "en-us"


[markup.highlight]
codeFences = false
style = "tango"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true


[params.reveal_hugo.templates.grey]
background = "#424242"
transition = "convex"
codeFences = false  # use highlight.js
